[package]
name = "valle-ffmpeg-sys"
description = "Runtime-loaded FFmpeg 7, 8 and 9 FFI bindings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license = "WTFPL AND LGPL-2.1-or-later"
readme = "README.md"
build = "build.rs"
links = "valle_ffmpeg"
keywords = ["ffmpeg", "multimedia", "ffi", "dynamic"]
categories = ["external-ffi-bindings", "multimedia"]

[lib]
doctest = false

[features]
default = ["avcodec", "avformat", "avfilter", "avdevice", "swresample", "swscale"]
avcodec = []
avformat = ["avcodec"]
avfilter = []
avdevice = ["avformat"]
swresample = []
swscale = []
non-exhaustive-enums = []

[dependencies]
libc.workspace = true
libloading = "0.9"

[build-dependencies]
bindgen = { version = "0.72", default-features = false, features = ["runtime"] }
syn = { version = "2", features = ["full"] }
quote = "1"
prettyplease = "0.2"
regex = "1"
